apiVersion: core/v1
kind: ConfigMap
metadata:
  name: deploying-microservice-ConfigMap
  namespace: deploying-microservice-namespace
data:
  APP_ENV: production
  LOG_LEVEL: debug
  MESSAGE: "Welcome to Kubernetes"

---

apiVersion: core/v1
kind: Secret
metadata:
  name: deploying-microservice-secrets
  namespace: deploying-microservice-namespace
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: PLACEHOLDER_AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: PLACEHOLDER_AWS_SECRET_ACCESS_KEY