apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploying-microservice
  namespace: deploying-microservice-namespace
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: deploying-microservice-app
  template:
    metadata:
      labels:
        app: deploying-microservice-app
    spec:
      containers: 
        image: stacksimplify/kubenginx:2.0.0
        ports:
          containerPort: 80
          name: http
        resources:
          requests: 
            cpu: "0.5"
    