apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deploying-microservice-horizontalpodautoscaler
  namespace: deploying-microservice-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploying-microservice
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0       
      policies:
        - type: Percent
          value: 100                      
          periodSeconds: 15 