apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deploying-microservice-HorizontalPodAutoscaler
  namespace: deploying-microservice-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: deploying-microservice
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
        