apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator
  namespace: deploying-microservice-namespace
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: busybox
          image: busybox:1.28
          command: ["/bin/sh", "-c"]
          args:
            - |
              timeout 200s sh -c 'while sleep 0.1; do wget -q -O- http://php-apache.deploying-microservice-namespace.svc.cluster.local; done'
      restartPolicy: Never
