apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: deploying-microservice-namespace
  name: app-resource-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-app-resource-reader-binding
  namespace: deploying-microservice-namespace
subjects:
- kind: ServiceAccount
  name: default
  namespace: deploying-microservice-namespace
roleRef:
  kind: Role
  name: app-resource-reader
  apiGroup: rbac.authorization.k8s.io
